name: Testing nginx if its in pr and hosting if in main

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs : 
  install-nginx:
    runs-on: self-hosted
  
  on-pull-request:
    runs-on : self-hosted
    if: github.event_name == 'pull_request'
    steps :
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-verison}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Testing nginx
        run : nginx -t
        